/*******************************************************************************
* Copyright (C) 2019-2023 Maxim Integrated Products, Inc., All rights Reserved.
*
* This software is protected by copyright laws of the United States and
* of foreign countries. This material may also be protected by patent laws
* and technology transfer regulations of the United States and of foreign
* countries. This software is furnished under a license agreement and/or a
* nondisclosure agreement and may only be used or reproduced in accordance
* with the terms of those agreements. Dissemination of this information to
* any party or parties not specified in the license agreement and/or
* nondisclosure agreement is expressly prohibited.
*
* The above copyright notice and this permission notice shall be included
* in all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
* OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
* IN NO EVENT SHALL MAXIM INTEGRATED BE LIABLE FOR ANY CLAIM, DAMAGES
* OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
* OTHER DEALINGS IN THE SOFTWARE.
*
* Except as contained in this notice, the name of Maxim Integrated
* Products, Inc. shall not be used except as stated in the Maxim Integrated
* Products, Inc. Branding Policy.
*
* The mere transfer of this software does not imply any licenses
* of trade secrets, proprietary technology, copyrights, patents,
* trademarks, maskwork rights, or any other form of intellectual
* property whatsoever. Maxim Integrated Products, Inc. retains all
* ownership rights.
*******************************************************************************/

// epidenet_b_v2.1
// This file was @generated by ai8xize.py --verbose --test-dir demos --prefix epidenet_b_v2.1 --checkpoint-file .\trained_custom\checkpoints\epidenet_b_v2.1_qat_best-q.pth.tar --config-file .\networks\epidenet_b.yaml --device MAX78000 --compact-data --softmax --sample-input .\trained_custom\sample_data\sample_chbmit_singlech_patient_2_leave_out_seizure_1_epidenet_b_v2.1.npy --overwrite --energy

// DO NOT EDIT - regenerate this file instead!

// Configuring 12 layers
// Input data: CHW
// Layer 0: 1x512, no pooling, conv1d with kernel size 4, stride 1, pad 2, ReLU, 4x513 output
// Layer 1: 4x513, no pooling, conv1d with kernel size 2, stride 1, pad 0, ReLU, 4x512 output
// Layer 2: 4x512x1, max pool 8x1 with stride 8/8, no convolution, 4x64x1 output
// Layer 3: 4x64, no pooling, conv1d with kernel size 9, stride 1, pad 2, ReLU, 16x60 output
// Layer 4: 16x60, no pooling, conv1d with kernel size 8, stride 1, pad 2, ReLU, 16x57 output
// Layer 5: 16x57, no pooling, conv1d with kernel size 3, stride 1, pad 2, ReLU, 16x59 output
// Layer 6: 16x59, no pooling, conv1d with kernel size 3, stride 1, pad 2, ReLU, 16x61 output
// Layer 7: 16x61, no pooling, conv1d with kernel size 3, stride 1, pad 2, ReLU, 16x63 output
// Layer 8: 16x63, no pooling, conv1d with kernel size 2, stride 1, pad 1, ReLU, 16x64 output
// Layer 9: 16x64x1, max pool 4x1 with stride 4/4, no convolution, 16x16x1 output
// Layer 10: 16x16x1, avg pool 16x1 with stride 1/1, no convolution, 16x1x1 output
// Layer 11: 16x1x1 flattened to 16x1x1, no pooling, linear, no activation, 2x1x1 output

#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <stdio.h>
#include "mxc.h"
#include "gcfr_regs.h"
#include "cnn.h"
#include "weights.h"

void CNN_ISR(void)
{
  // Acknowledge interrupt to all quadrants
  *((volatile uint32_t *) 0x50100000) &= ~((1<<12) | 1);
  *((volatile uint32_t *) 0x50500000) &= ~((1<<12) | 1);
  *((volatile uint32_t *) 0x50900000) &= ~((1<<12) | 1);
  *((volatile uint32_t *) 0x50d00000) &= ~((1<<12) | 1);

#ifdef CNN_INFERENCE_TIMER
  cnn_time = MXC_TMR_SW_Stop(CNN_INFERENCE_TIMER);
#else
  cnn_time = 1;
#endif
}

int cnn_continue(void)
{
  cnn_time = 0;

  *((volatile uint32_t *) 0x50100000) |= 1; // Re-enable quadrant 0

  return CNN_OK;
}

int cnn_stop(void)
{
  *((volatile uint32_t *) 0x50100000) &= ~1; // Disable quadrant 0

  return CNN_OK;
}

void memcpy32(uint32_t *dst, const uint32_t *src, int n)
{
  while (n-- > 0) {
    *dst++ = *src++;
  }
}

static const uint32_t kernels[] = KERNELS;

int cnn_load_weights(void)
{
  uint32_t len;
  volatile uint32_t *addr;
  const uint32_t *ptr = kernels;

  while ((addr = (volatile uint32_t *) *ptr++) != 0) {
    *((volatile uint8_t *) ((uint32_t) addr | 1)) = 0x01; // Set address
    len = *ptr++;
    while (len-- > 0)
      *addr++ = *ptr++;
  }

  return CNN_OK;
}

static const uint8_t bias_0[] = BIAS_0;
static const uint8_t bias_1[] = BIAS_1;
static const uint8_t bias_2[] = BIAS_2;
static const uint8_t bias_3[] = BIAS_3;

static void memcpy_8to32(uint32_t *dst, const uint8_t *src, int n)
{
  while (n-- > 0) {
    *dst++ = *src++;
  }
}

int cnn_load_bias(void)
{
  memcpy_8to32((uint32_t *) 0x50108000, bias_0, sizeof(uint8_t) * 32);
  memcpy_8to32((uint32_t *) 0x50508000, bias_1, sizeof(uint8_t) * 32);
  memcpy_8to32((uint32_t *) 0x50908000, bias_2, sizeof(uint8_t) * 20);
  memcpy_8to32((uint32_t *) 0x50d08000, bias_3, sizeof(uint8_t) * 20);

  return CNN_OK;
}

int cnn_init(void)
{
  *((volatile uint32_t *) 0x50001000) = 0x00000000; // AON control
  *((volatile uint32_t *) 0x50100000) = 0x00100008; // Stop SM
  *((volatile uint32_t *) 0x50100004) = 0x0000040e; // SRAM control
  *((volatile uint32_t *) 0x50100008) = 0x0000000b; // Layer count
  *((volatile uint32_t *) 0x50500000) = 0x00100008; // Stop SM
  *((volatile uint32_t *) 0x50500004) = 0x0000040e; // SRAM control
  *((volatile uint32_t *) 0x50500008) = 0x0000000b; // Layer count
  *((volatile uint32_t *) 0x50900000) = 0x00100008; // Stop SM
  *((volatile uint32_t *) 0x50900004) = 0x0000040e; // SRAM control
  *((volatile uint32_t *) 0x50900008) = 0x0000000b; // Layer count
  *((volatile uint32_t *) 0x50d00000) = 0x00100008; // Stop SM
  *((volatile uint32_t *) 0x50d00004) = 0x0000040e; // SRAM control
  *((volatile uint32_t *) 0x50d00008) = 0x0000000b; // Layer count

  return CNN_OK;
}

int cnn_configure(void)
{
  // Layer 0 quadrant 0
  *((volatile uint32_t *) 0x50100010) = 0x00020203; // Rows
  *((volatile uint32_t *) 0x50100310) = 0x00002000; // SRAM write ptr
  *((volatile uint32_t *) 0x50100410) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50100590) = 0x00004b60; // Layer control
  *((volatile uint32_t *) 0x50100a10) = 0x00001800; // Layer control 2
  *((volatile uint32_t *) 0x50100610) = 0x00000018; // Mask offset and count
  *((volatile uint32_t *) 0x50100110) = 0x00001400; // 1D
  *((volatile uint32_t *) 0x50100790) = 0x00006000; // Post processing register
  *((volatile uint32_t *) 0x50100710) = 0x00010001; // Mask and processor enables

  // Layer 0 quadrant 1
  *((volatile uint32_t *) 0x50500010) = 0x00020203; // Rows
  *((volatile uint32_t *) 0x50500310) = 0x00002000; // SRAM write ptr
  *((volatile uint32_t *) 0x50500410) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50500590) = 0x00000b60; // Layer control
  *((volatile uint32_t *) 0x50500a10) = 0x00001800; // Layer control 2
  *((volatile uint32_t *) 0x50500610) = 0x00000018; // Mask offset and count
  *((volatile uint32_t *) 0x50500110) = 0x00001400; // 1D
  *((volatile uint32_t *) 0x50500790) = 0x00006000; // Post processing register

  // Layer 0 quadrant 2
  *((volatile uint32_t *) 0x50900010) = 0x00020203; // Rows
  *((volatile uint32_t *) 0x50900310) = 0x00002000; // SRAM write ptr
  *((volatile uint32_t *) 0x50900410) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50900590) = 0x00000b60; // Layer control
  *((volatile uint32_t *) 0x50900a10) = 0x00001800; // Layer control 2
  *((volatile uint32_t *) 0x50900610) = 0x00000018; // Mask offset and count
  *((volatile uint32_t *) 0x50900110) = 0x00001400; // 1D
  *((volatile uint32_t *) 0x50900790) = 0x00007010; // Post processing register

  // Layer 0 quadrant 3
  *((volatile uint32_t *) 0x50d00010) = 0x00020203; // Rows
  *((volatile uint32_t *) 0x50d00310) = 0x00002000; // SRAM write ptr
  *((volatile uint32_t *) 0x50d00410) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d00590) = 0x00000b60; // Layer control
  *((volatile uint32_t *) 0x50d00a10) = 0x00001800; // Layer control 2
  *((volatile uint32_t *) 0x50d00610) = 0x00000018; // Mask offset and count
  *((volatile uint32_t *) 0x50d00110) = 0x00001400; // 1D
  *((volatile uint32_t *) 0x50d00790) = 0x00006000; // Post processing register

  // Layer 1 quadrant 0
  *((volatile uint32_t *) 0x50100014) = 0x00000200; // Rows
  *((volatile uint32_t *) 0x50100314) = 0x00004000; // SRAM write ptr
  *((volatile uint32_t *) 0x50100414) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50100594) = 0x00008b20; // Layer control
  *((volatile uint32_t *) 0x50100a14) = 0x00001800; // Layer control 2
  *((volatile uint32_t *) 0x50100614) = 0x00000018; // Mask offset and count
  *((volatile uint32_t *) 0x50100114) = 0x00001200; // 1D
  *((volatile uint32_t *) 0x50100794) = 0x00002000; // Post processing register
  *((volatile uint32_t *) 0x50100714) = 0x00f000f0; // Mask and processor enables

  // Layer 1 quadrant 1
  *((volatile uint32_t *) 0x50500014) = 0x00000200; // Rows
  *((volatile uint32_t *) 0x50500314) = 0x00004000; // SRAM write ptr
  *((volatile uint32_t *) 0x50500414) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50500594) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a14) = 0x00001800; // Layer control 2
  *((volatile uint32_t *) 0x50500614) = 0x00000018; // Mask offset and count
  *((volatile uint32_t *) 0x50500114) = 0x00001200; // 1D
  *((volatile uint32_t *) 0x50500794) = 0x00002000; // Post processing register

  // Layer 1 quadrant 2
  *((volatile uint32_t *) 0x50900014) = 0x00000200; // Rows
  *((volatile uint32_t *) 0x50900314) = 0x00004000; // SRAM write ptr
  *((volatile uint32_t *) 0x50900414) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50900594) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a14) = 0x00001800; // Layer control 2
  *((volatile uint32_t *) 0x50900614) = 0x00000018; // Mask offset and count
  *((volatile uint32_t *) 0x50900114) = 0x00001200; // 1D
  *((volatile uint32_t *) 0x50900794) = 0x00002000; // Post processing register

  // Layer 1 quadrant 3
  *((volatile uint32_t *) 0x50d00014) = 0x00000200; // Rows
  *((volatile uint32_t *) 0x50d00314) = 0x00004000; // SRAM write ptr
  *((volatile uint32_t *) 0x50d00414) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d00594) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a14) = 0x00001800; // Layer control 2
  *((volatile uint32_t *) 0x50d00614) = 0x00000018; // Mask offset and count
  *((volatile uint32_t *) 0x50d00114) = 0x00001200; // 1D
  *((volatile uint32_t *) 0x50d00794) = 0x00003010; // Post processing register

  // Layer 2 quadrant 0
  *((volatile uint32_t *) 0x50100018) = 0x000001ff; // Rows
  *((volatile uint32_t *) 0x50100198) = 0x00000007; // Pooling rows
  *((volatile uint32_t *) 0x50100298) = 0x00000007; // Stride
  *((volatile uint32_t *) 0x50100318) = 0x00006000; // SRAM write ptr
  *((volatile uint32_t *) 0x50100398) = 0x00000800; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50100598) = 0x000009a0; // Layer control
  *((volatile uint32_t *) 0x50100118) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x50100798) = 0x03000000; // Post processing register
  *((volatile uint32_t *) 0x50100718) = 0x00000f00; // Mask and processor enables

  // Layer 2 quadrant 1
  *((volatile uint32_t *) 0x50500018) = 0x000001ff; // Rows
  *((volatile uint32_t *) 0x50500198) = 0x00000007; // Pooling rows
  *((volatile uint32_t *) 0x50500298) = 0x00000007; // Stride
  *((volatile uint32_t *) 0x50500398) = 0x00000800; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50500598) = 0x000009a0; // Layer control
  *((volatile uint32_t *) 0x50500118) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x50500798) = 0x03000000; // Post processing register

  // Layer 2 quadrant 2
  *((volatile uint32_t *) 0x50900018) = 0x000001ff; // Rows
  *((volatile uint32_t *) 0x50900198) = 0x00000007; // Pooling rows
  *((volatile uint32_t *) 0x50900298) = 0x00000007; // Stride
  *((volatile uint32_t *) 0x50900398) = 0x00000800; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50900598) = 0x000009a0; // Layer control
  *((volatile uint32_t *) 0x50900118) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x50900798) = 0x03000000; // Post processing register

  // Layer 2 quadrant 3
  *((volatile uint32_t *) 0x50d00018) = 0x000001ff; // Rows
  *((volatile uint32_t *) 0x50d00198) = 0x00000007; // Pooling rows
  *((volatile uint32_t *) 0x50d00298) = 0x00000007; // Stride
  *((volatile uint32_t *) 0x50d00398) = 0x00000800; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50d00598) = 0x000009a0; // Layer control
  *((volatile uint32_t *) 0x50d00118) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x50d00798) = 0x03000000; // Post processing register

  // Layer 3 quadrant 0
  *((volatile uint32_t *) 0x5010001c) = 0x00020043; // Rows
  *((volatile uint32_t *) 0x5010031c) = 0x00008000; // SRAM write ptr
  *((volatile uint32_t *) 0x5010041c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x5010059c) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50100a1c) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x5010061c) = 0x00000078; // Mask offset and count
  *((volatile uint32_t *) 0x5010011c) = 0x00001900; // 1D
  *((volatile uint32_t *) 0x5010079c) = 0x00023000; // Post processing register
  *((volatile uint32_t *) 0x5010071c) = 0xf000f000; // Mask and processor enables

  // Layer 3 quadrant 1
  *((volatile uint32_t *) 0x5050001c) = 0x00020043; // Rows
  *((volatile uint32_t *) 0x5050031c) = 0x00008000; // SRAM write ptr
  *((volatile uint32_t *) 0x5050041c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x5050059c) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a1c) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x5050061c) = 0x00000078; // Mask offset and count
  *((volatile uint32_t *) 0x5050011c) = 0x00001900; // 1D
  *((volatile uint32_t *) 0x5050079c) = 0x00022000; // Post processing register

  // Layer 3 quadrant 2
  *((volatile uint32_t *) 0x5090001c) = 0x00020043; // Rows
  *((volatile uint32_t *) 0x5090031c) = 0x00008000; // SRAM write ptr
  *((volatile uint32_t *) 0x5090041c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x5090059c) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a1c) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x5090061c) = 0x00000078; // Mask offset and count
  *((volatile uint32_t *) 0x5090011c) = 0x00001900; // 1D
  *((volatile uint32_t *) 0x5090079c) = 0x00022000; // Post processing register

  // Layer 3 quadrant 3
  *((volatile uint32_t *) 0x50d0001c) = 0x00020043; // Rows
  *((volatile uint32_t *) 0x50d0031c) = 0x00008000; // SRAM write ptr
  *((volatile uint32_t *) 0x50d0041c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d0059c) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a1c) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50d0061c) = 0x00000078; // Mask offset and count
  *((volatile uint32_t *) 0x50d0011c) = 0x00001900; // 1D
  *((volatile uint32_t *) 0x50d0079c) = 0x00022000; // Post processing register

  // Layer 4 quadrant 0
  *((volatile uint32_t *) 0x50100020) = 0x0002003f; // Rows
  *((volatile uint32_t *) 0x50100320) = 0x00010000; // SRAM write ptr
  *((volatile uint32_t *) 0x50100420) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x501005a0) = 0x00002b20; // Layer control
  *((volatile uint32_t *) 0x50100a20) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50100620) = 0x00000078; // Mask offset and count
  *((volatile uint32_t *) 0x50100120) = 0x00001800; // 1D
  *((volatile uint32_t *) 0x501007a0) = 0x00022000; // Post processing register

  // Layer 4 quadrant 1
  *((volatile uint32_t *) 0x50500020) = 0x0002003f; // Rows
  *((volatile uint32_t *) 0x50500320) = 0x00010000; // SRAM write ptr
  *((volatile uint32_t *) 0x50500420) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x505005a0) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a20) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50500620) = 0x00000078; // Mask offset and count
  *((volatile uint32_t *) 0x50500120) = 0x00001800; // 1D
  *((volatile uint32_t *) 0x505007a0) = 0x00023000; // Post processing register
  *((volatile uint32_t *) 0x50500720) = 0xffffffff; // Mask and processor enables

  // Layer 4 quadrant 2
  *((volatile uint32_t *) 0x50900020) = 0x0002003f; // Rows
  *((volatile uint32_t *) 0x50900320) = 0x00010000; // SRAM write ptr
  *((volatile uint32_t *) 0x50900420) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x509005a0) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a20) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50900620) = 0x00000078; // Mask offset and count
  *((volatile uint32_t *) 0x50900120) = 0x00001800; // 1D
  *((volatile uint32_t *) 0x509007a0) = 0x00022000; // Post processing register

  // Layer 4 quadrant 3
  *((volatile uint32_t *) 0x50d00020) = 0x0002003f; // Rows
  *((volatile uint32_t *) 0x50d00320) = 0x00010000; // SRAM write ptr
  *((volatile uint32_t *) 0x50d00420) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d005a0) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a20) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50d00620) = 0x00000078; // Mask offset and count
  *((volatile uint32_t *) 0x50d00120) = 0x00001800; // 1D
  *((volatile uint32_t *) 0x50d007a0) = 0x00022000; // Post processing register

  // Layer 5 quadrant 0
  *((volatile uint32_t *) 0x50100024) = 0x0002003c; // Rows
  *((volatile uint32_t *) 0x50100324) = 0x00018000; // SRAM write ptr
  *((volatile uint32_t *) 0x50100424) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x501005a4) = 0x00004b20; // Layer control
  *((volatile uint32_t *) 0x50100a24) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50100624) = 0x00000078; // Mask offset and count
  *((volatile uint32_t *) 0x50100124) = 0x00001300; // 1D

  // Layer 5 quadrant 1
  *((volatile uint32_t *) 0x50500024) = 0x0002003c; // Rows
  *((volatile uint32_t *) 0x50500324) = 0x00018000; // SRAM write ptr
  *((volatile uint32_t *) 0x50500424) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x505005a4) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a24) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50500624) = 0x00000078; // Mask offset and count
  *((volatile uint32_t *) 0x50500124) = 0x00001300; // 1D

  // Layer 5 quadrant 2
  *((volatile uint32_t *) 0x50900024) = 0x0002003c; // Rows
  *((volatile uint32_t *) 0x50900324) = 0x00018000; // SRAM write ptr
  *((volatile uint32_t *) 0x50900424) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x509005a4) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a24) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50900624) = 0x00000078; // Mask offset and count
  *((volatile uint32_t *) 0x50900124) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x509007a4) = 0x00001000; // Post processing register
  *((volatile uint32_t *) 0x50900724) = 0xffffffff; // Mask and processor enables

  // Layer 5 quadrant 3
  *((volatile uint32_t *) 0x50d00024) = 0x0002003c; // Rows
  *((volatile uint32_t *) 0x50d00324) = 0x00018000; // SRAM write ptr
  *((volatile uint32_t *) 0x50d00424) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d005a4) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a24) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50d00624) = 0x00000078; // Mask offset and count
  *((volatile uint32_t *) 0x50d00124) = 0x00001300; // 1D

  // Layer 6 quadrant 0
  *((volatile uint32_t *) 0x50100028) = 0x0002003e; // Rows
  *((volatile uint32_t *) 0x50100428) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x501005a8) = 0x00008b20; // Layer control
  *((volatile uint32_t *) 0x50100a28) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50100628) = 0x00000078; // Mask offset and count
  *((volatile uint32_t *) 0x50100128) = 0x00001300; // 1D

  // Layer 6 quadrant 1
  *((volatile uint32_t *) 0x50500028) = 0x0002003e; // Rows
  *((volatile uint32_t *) 0x50500428) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x505005a8) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a28) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50500628) = 0x00000078; // Mask offset and count
  *((volatile uint32_t *) 0x50500128) = 0x00001300; // 1D

  // Layer 6 quadrant 2
  *((volatile uint32_t *) 0x50900028) = 0x0002003e; // Rows
  *((volatile uint32_t *) 0x50900428) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x509005a8) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a28) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50900628) = 0x00000078; // Mask offset and count
  *((volatile uint32_t *) 0x50900128) = 0x00001300; // 1D

  // Layer 6 quadrant 3
  *((volatile uint32_t *) 0x50d00028) = 0x0002003e; // Rows
  *((volatile uint32_t *) 0x50d00428) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d005a8) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a28) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50d00628) = 0x00000078; // Mask offset and count
  *((volatile uint32_t *) 0x50d00128) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x50d007a8) = 0x00001000; // Post processing register
  *((volatile uint32_t *) 0x50d00728) = 0xffffffff; // Mask and processor enables

  // Layer 7 quadrant 0
  *((volatile uint32_t *) 0x5010002c) = 0x00020040; // Rows
  *((volatile uint32_t *) 0x5010032c) = 0x00008000; // SRAM write ptr
  *((volatile uint32_t *) 0x5010042c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x501005ac) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50100a2c) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x5010062c) = 0x018001f8; // Mask offset and count
  *((volatile uint32_t *) 0x5010012c) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x501007ac) = 0x00001010; // Post processing register
  *((volatile uint32_t *) 0x5010072c) = 0xffffffff; // Mask and processor enables

  // Layer 7 quadrant 1
  *((volatile uint32_t *) 0x5050002c) = 0x00020040; // Rows
  *((volatile uint32_t *) 0x5050032c) = 0x00008000; // SRAM write ptr
  *((volatile uint32_t *) 0x5050042c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x505005ac) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a2c) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x5050062c) = 0x018001f8; // Mask offset and count
  *((volatile uint32_t *) 0x5050012c) = 0x00001300; // 1D

  // Layer 7 quadrant 2
  *((volatile uint32_t *) 0x5090002c) = 0x00020040; // Rows
  *((volatile uint32_t *) 0x5090032c) = 0x00008000; // SRAM write ptr
  *((volatile uint32_t *) 0x5090042c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x509005ac) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a2c) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x5090062c) = 0x018001f8; // Mask offset and count
  *((volatile uint32_t *) 0x5090012c) = 0x00001300; // 1D

  // Layer 7 quadrant 3
  *((volatile uint32_t *) 0x50d0002c) = 0x00020040; // Rows
  *((volatile uint32_t *) 0x50d0032c) = 0x00008000; // SRAM write ptr
  *((volatile uint32_t *) 0x50d0042c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d005ac) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a2c) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50d0062c) = 0x018001f8; // Mask offset and count
  *((volatile uint32_t *) 0x50d0012c) = 0x00001300; // 1D

  // Layer 8 quadrant 0
  *((volatile uint32_t *) 0x50100030) = 0x00010040; // Rows
  *((volatile uint32_t *) 0x50100330) = 0x00010000; // SRAM write ptr
  *((volatile uint32_t *) 0x50100430) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x501005b0) = 0x00002b20; // Layer control
  *((volatile uint32_t *) 0x50100a30) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50100630) = 0x024002b8; // Mask offset and count
  *((volatile uint32_t *) 0x50100130) = 0x00001200; // 1D

  // Layer 8 quadrant 1
  *((volatile uint32_t *) 0x50500030) = 0x00010040; // Rows
  *((volatile uint32_t *) 0x50500330) = 0x00010000; // SRAM write ptr
  *((volatile uint32_t *) 0x50500430) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x505005b0) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a30) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50500630) = 0x024002b8; // Mask offset and count
  *((volatile uint32_t *) 0x50500130) = 0x00001200; // 1D
  *((volatile uint32_t *) 0x505007b0) = 0x00001010; // Post processing register
  *((volatile uint32_t *) 0x50500730) = 0xffffffff; // Mask and processor enables

  // Layer 8 quadrant 2
  *((volatile uint32_t *) 0x50900030) = 0x00010040; // Rows
  *((volatile uint32_t *) 0x50900330) = 0x00010000; // SRAM write ptr
  *((volatile uint32_t *) 0x50900430) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x509005b0) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a30) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50900630) = 0x024002b8; // Mask offset and count
  *((volatile uint32_t *) 0x50900130) = 0x00001200; // 1D

  // Layer 8 quadrant 3
  *((volatile uint32_t *) 0x50d00030) = 0x00010040; // Rows
  *((volatile uint32_t *) 0x50d00330) = 0x00010000; // SRAM write ptr
  *((volatile uint32_t *) 0x50d00430) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d005b0) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a30) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50d00630) = 0x024002b8; // Mask offset and count
  *((volatile uint32_t *) 0x50d00130) = 0x00001200; // 1D

  // Layer 9 quadrant 0
  *((volatile uint32_t *) 0x50100034) = 0x0000003f; // Rows
  *((volatile uint32_t *) 0x501001b4) = 0x00000003; // Pooling rows
  *((volatile uint32_t *) 0x501002b4) = 0x00000003; // Stride
  *((volatile uint32_t *) 0x50100334) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x501003b4) = 0x00002000; // Write ptr time slot offs
  *((volatile uint32_t *) 0x501005b4) = 0x000009a0; // Layer control
  *((volatile uint32_t *) 0x50100134) = 0x00000103; // 1D
  *((volatile uint32_t *) 0x501007b4) = 0x03000000; // Post processing register

  // Layer 9 quadrant 1
  *((volatile uint32_t *) 0x50500034) = 0x0000003f; // Rows
  *((volatile uint32_t *) 0x505001b4) = 0x00000003; // Pooling rows
  *((volatile uint32_t *) 0x505002b4) = 0x00000003; // Stride
  *((volatile uint32_t *) 0x50500334) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x505003b4) = 0x00002000; // Write ptr time slot offs
  *((volatile uint32_t *) 0x505005b4) = 0x000009a0; // Layer control
  *((volatile uint32_t *) 0x50500134) = 0x00000103; // 1D
  *((volatile uint32_t *) 0x505007b4) = 0x03000000; // Post processing register

  // Layer 9 quadrant 2
  *((volatile uint32_t *) 0x50900034) = 0x0000003f; // Rows
  *((volatile uint32_t *) 0x509001b4) = 0x00000003; // Pooling rows
  *((volatile uint32_t *) 0x509002b4) = 0x00000003; // Stride
  *((volatile uint32_t *) 0x50900334) = 0x00010800; // SRAM write ptr
  *((volatile uint32_t *) 0x509003b4) = 0x00002000; // Write ptr time slot offs
  *((volatile uint32_t *) 0x509005b4) = 0x000009a0; // Layer control
  *((volatile uint32_t *) 0x50900134) = 0x00000103; // 1D
  *((volatile uint32_t *) 0x509007b4) = 0x03000000; // Post processing register
  *((volatile uint32_t *) 0x50900734) = 0x0000ffff; // Mask and processor enables

  // Layer 9 quadrant 3
  *((volatile uint32_t *) 0x50d00034) = 0x0000003f; // Rows
  *((volatile uint32_t *) 0x50d001b4) = 0x00000003; // Pooling rows
  *((volatile uint32_t *) 0x50d002b4) = 0x00000003; // Stride
  *((volatile uint32_t *) 0x50d00334) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x50d003b4) = 0x00002000; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50d005b4) = 0x000009a0; // Layer control
  *((volatile uint32_t *) 0x50d00134) = 0x00000103; // 1D
  *((volatile uint32_t *) 0x50d007b4) = 0x03000000; // Post processing register

  // Layer 10 quadrant 0
  *((volatile uint32_t *) 0x50100038) = 0x0000000f; // Rows
  *((volatile uint32_t *) 0x501001b8) = 0x0000000f; // Pooling rows
  *((volatile uint32_t *) 0x501003b8) = 0x00002000; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50100538) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x501005b8) = 0x000008a0; // Layer control
  *((volatile uint32_t *) 0x50100138) = 0x00000103; // 1D
  *((volatile uint32_t *) 0x501007b8) = 0x03000000; // Post processing register

  // Layer 10 quadrant 1
  *((volatile uint32_t *) 0x50500038) = 0x0000000f; // Rows
  *((volatile uint32_t *) 0x505001b8) = 0x0000000f; // Pooling rows
  *((volatile uint32_t *) 0x505003b8) = 0x00002000; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50500538) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x505005b8) = 0x000008a0; // Layer control
  *((volatile uint32_t *) 0x50500138) = 0x00000103; // 1D
  *((volatile uint32_t *) 0x505007b8) = 0x03000000; // Post processing register

  // Layer 10 quadrant 2
  *((volatile uint32_t *) 0x50900038) = 0x0000000f; // Rows
  *((volatile uint32_t *) 0x509001b8) = 0x0000000f; // Pooling rows
  *((volatile uint32_t *) 0x50900338) = 0x00010000; // SRAM write ptr
  *((volatile uint32_t *) 0x509003b8) = 0x00002000; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50900538) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x509005b8) = 0x000008a0; // Layer control
  *((volatile uint32_t *) 0x50900138) = 0x00000103; // 1D
  *((volatile uint32_t *) 0x509007b8) = 0x03000000; // Post processing register
  *((volatile uint32_t *) 0x50900738) = 0x0000ffff; // Mask and processor enables

  // Layer 10 quadrant 3
  *((volatile uint32_t *) 0x50d00038) = 0x0000000f; // Rows
  *((volatile uint32_t *) 0x50d001b8) = 0x0000000f; // Pooling rows
  *((volatile uint32_t *) 0x50d003b8) = 0x00002000; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50d00538) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x50d005b8) = 0x000008a0; // Layer control
  *((volatile uint32_t *) 0x50d00138) = 0x00000103; // 1D
  *((volatile uint32_t *) 0x50d007b8) = 0x03000000; // Post processing register

  // Layer 11 quadrant 0
  *((volatile uint32_t *) 0x501003bc) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x5010043c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x501005bc) = 0x00014920; // Layer control
  *((volatile uint32_t *) 0x50100a3c) = 0x00000800; // Layer control 2
  *((volatile uint32_t *) 0x5010063c) = 0x02400248; // Mask offset and count
  *((volatile uint32_t *) 0x5010013c) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x501007bc) = 0x00022000; // Post processing register

  // Layer 11 quadrant 1
  *((volatile uint32_t *) 0x505003bc) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x5050043c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x505005bc) = 0x00010920; // Layer control
  *((volatile uint32_t *) 0x50500a3c) = 0x00000800; // Layer control 2
  *((volatile uint32_t *) 0x5050063c) = 0x02400248; // Mask offset and count
  *((volatile uint32_t *) 0x5050013c) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x505007bc) = 0x00022000; // Post processing register

  // Layer 11 quadrant 2
  *((volatile uint32_t *) 0x509003bc) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x5090043c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x509005bc) = 0x00010920; // Layer control
  *((volatile uint32_t *) 0x50900a3c) = 0x00000800; // Layer control 2
  *((volatile uint32_t *) 0x5090063c) = 0x02400248; // Mask offset and count
  *((volatile uint32_t *) 0x5090013c) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x509007bc) = 0x00022000; // Post processing register
  *((volatile uint32_t *) 0x5090073c) = 0xffffffff; // Mask and processor enables

  // Layer 11 quadrant 3
  *((volatile uint32_t *) 0x50d003bc) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50d0043c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d005bc) = 0x00010920; // Layer control
  *((volatile uint32_t *) 0x50d00a3c) = 0x00000800; // Layer control 2
  *((volatile uint32_t *) 0x50d0063c) = 0x02400248; // Mask offset and count
  *((volatile uint32_t *) 0x50d0013c) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x50d007bc) = 0x00022000; // Post processing register


  return CNN_OK;
}

int cnn_start(void)
{
  cnn_time = 0;

  *((volatile uint32_t *) 0x50100000) = 0x00100808; // Enable quadrant 0
  *((volatile uint32_t *) 0x50500000) = 0x00100809; // Enable quadrant 1
  *((volatile uint32_t *) 0x50900000) = 0x00100809; // Enable quadrant 2
  *((volatile uint32_t *) 0x50d00000) = 0x00100809; // Enable quadrant 3

#ifdef CNN_INFERENCE_TIMER
  MXC_TMR_SW_Start(CNN_INFERENCE_TIMER);
#endif

  *((volatile uint32_t *) 0x50100000) = 0x00100009; // Master enable quadrant 0

  return CNN_OK;
}

int cnn_unload(uint32_t *out_buf)
{
  volatile uint32_t *addr;

  // Custom unload for this network, layer 11 (block6_dense): 32-bit data, shape: (2, 1, 1)
  addr = (volatile uint32_t *) 0x50400000;
  *out_buf++ = *addr++;
  *out_buf++ = *addr++;

  return CNN_OK;
}

int cnn_enable(uint32_t clock_source, uint32_t clock_divider)
{
  // Reset all domains, restore power to CNN
  MXC_GCFR->reg3 = 0xf; // Reset
  MXC_GCFR->reg1 = 0xf; // Mask memory
  MXC_GCFR->reg0 = 0xf; // Power
  MXC_GCFR->reg2 = 0x0; // Iso
  MXC_GCFR->reg3 = 0x0; // Reset

  MXC_GCR->pclkdiv = (MXC_GCR->pclkdiv & ~(MXC_F_GCR_PCLKDIV_CNNCLKDIV | MXC_F_GCR_PCLKDIV_CNNCLKSEL))
                     | clock_divider | clock_source;
  MXC_SYS_ClockEnable(MXC_SYS_PERIPH_CLOCK_CNN); // Enable CNN clock

  MXC_NVIC_SetVector(CNN_IRQn, CNN_ISR); // Set CNN complete vector

  return CNN_OK;
}

int cnn_boost_enable(mxc_gpio_regs_t *port, uint32_t pin)
{
  mxc_gpio_cfg_t gpio_out;
  gpio_out.port = port;
  gpio_out.mask = pin;
  gpio_out.pad = MXC_GPIO_PAD_NONE;
  gpio_out.func = MXC_GPIO_FUNC_OUT;
  MXC_GPIO_Config(&gpio_out);
  MXC_GPIO_OutSet(gpio_out.port, gpio_out.mask);

  return CNN_OK;
}

int cnn_boost_disable(mxc_gpio_regs_t *port, uint32_t pin)
{
  mxc_gpio_cfg_t gpio_out;
  gpio_out.port = port;
  gpio_out.mask = pin;
  gpio_out.pad = MXC_GPIO_PAD_NONE;
  gpio_out.func = MXC_GPIO_FUNC_OUT;
  MXC_GPIO_Config(&gpio_out);
  MXC_GPIO_OutClr(gpio_out.port, gpio_out.mask);

  return CNN_OK;
}

int cnn_disable(void)
{
  // Disable CNN clock
  MXC_SYS_ClockDisable(MXC_SYS_PERIPH_CLOCK_CNN);

  // Disable power to CNN
  MXC_GCFR->reg3 = 0xf; // Reset
  MXC_GCFR->reg2 |= 0xf; // Iso
  MXC_GCFR->reg0 = 0x0; // Power
  MXC_GCFR->reg1 = 0x0; // Mask memory
  MXC_GCFR->reg3 = 0x0; // Reset

  return CNN_OK;
}

